#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"

export UV_CACHE_DIR="${UV_CACHE_DIR:-/tmp/reposeed-uv-cache}"
export npm_config_cache="${npm_config_cache:-/tmp/reposeed-npm-cache}"

assert_file_contains() {
  local file_path="$1"
  local expected="$2"

  if [[ "$(<"$file_path")" != *"$expected"* ]]; then
    printf 'Expected %s to contain: %s\n' "$file_path" "$expected" >&2
    exit 1
  fi
}

assert_file_not_contains() {
  local file_path="$1"
  local unexpected="$2"

  if [[ "$(<"$file_path")" == *"$unexpected"* ]]; then
    printf 'Expected %s not to contain: %s\n' "$file_path" "$unexpected" >&2
    exit 1
  fi
}

prepend_fake_uv() {
  local fake_bin="$1"

  mkdir -p "$fake_bin"
  cat >"$fake_bin/uv" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

if [[ "${1-}" == "init" ]]; then
  project_dir="."
  package_name="python_project"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --name)
        package_name="${2//-/_}"
        shift 2
        ;;
      --vcs|--python)
        shift 2
        ;;
      --package)
        shift
        ;;
      init)
        shift
        ;;
      *)
        project_dir="$1"
        shift
        ;;
    esac
  done

  mkdir -p "$project_dir/src/$package_name"
  printf '[project]\nname = "%s"\nversion = "0.1.0"\n' "$package_name" >"$project_dir/pyproject.toml"
  printf 'def project_name() -> str:\n    return "%s"\n' "$package_name" >"$project_dir/src/$package_name/__init__.py"
  exit 0
fi

exit 0
EOF
  chmod +x "$fake_bin/uv"
  export PATH="$fake_bin:$PATH"
}

run_bash_install_contract() {
  local tmp_root bin_dir data_dir wrapper

  tmp_root="$(mktemp -d)"
  bin_dir="$tmp_root/bin"
  data_dir="$tmp_root/data"
  wrapper="$bin_dir/reposeed-test"

  "$ROOT/install.sh" \
    --bin-dir "$bin_dir" \
    --data-dir "$data_dir" \
    --command reposeed-test

  [[ -x "$wrapper" ]] || {
    printf 'Expected executable wrapper: %s\n' "$wrapper" >&2
    exit 1
  }
  [[ -f "$data_dir/new-project.sh" ]] || {
    printf 'Expected Bash scaffolder in payload.\n' >&2
    exit 1
  }
  [[ -f "$data_dir/new-project.ps1" ]] || {
    printf 'Expected PowerShell scaffolder in payload.\n' >&2
    exit 1
  }
  [[ -d "$data_dir/templates" ]] || {
    printf 'Expected templates in payload.\n' >&2
    exit 1
  }

  assert_file_contains "$wrapper" 'new-project.sh'
}

run_windows_installer_static_contract() {
  local installer_path="$ROOT/install.ps1"

  [[ -f "$installer_path" ]] || {
    printf 'Expected Windows installer: %s\n' "$installer_path" >&2
    exit 1
  }

  assert_file_contains "$installer_path" 'Microsoft\WindowsApps'
  assert_file_contains "$installer_path" 'RepoSeed'
  assert_file_contains "$installer_path" 'new-project.ps1'
  assert_file_contains "$installer_path" '$Command.ps1'
}

run_agents_contract() {
  local tmp_root project_dir agents_path

  tmp_root="$(mktemp -d)"
  prepend_fake_uv "$tmp_root/bin"
  project_dir="$tmp_root/bash-agents-demo"
  agents_path="$project_dir/AGENTS.md"
  mkdir -p "$project_dir"

  pushd "$project_dir" >/dev/null
  "$ROOT/new-project.sh" \
    --name bash-agents-demo \
    --no-git \
    --no-install-hooks \
    --no-github-actions
  popd >/dev/null

  assert_file_contains "$agents_path" 'This project was generated by `new-project.sh`.'
  assert_file_contains "$agents_path" 'Primary shell: Bash'
  assert_file_contains "$agents_path" './scripts/check.sh'
  assert_file_contains "$agents_path" './scripts/fix.sh'
  assert_file_not_contains "$agents_path" 'Windows PowerShell'
  assert_file_not_contains "$agents_path" '.\scripts\check.ps1'
}

run_powershell_contract_if_available() {
  if ! command -v pwsh >/dev/null 2>&1; then
    printf 'Skipping PowerShell contract: pwsh not found\n'
    return
  fi

  pwsh -NoProfile -File "$ROOT/new-project.ps1" -? >/dev/null
  pwsh -NoProfile -File "$ROOT/install.ps1" -? >/dev/null

  local tmp_root project_dir agents_path
  tmp_root="$(mktemp -d)"
  prepend_fake_uv "$tmp_root/bin"
  project_dir="$tmp_root/ps-agents-demo"
  agents_path="$project_dir/AGENTS.md"
  mkdir -p "$project_dir"

  pushd "$project_dir" >/dev/null
  pwsh -NoProfile -File "$ROOT/new-project.ps1" \
    -Name ps-agents-demo \
    -NoGit \
    -NoInstallHooks \
    -NoGitHubActions
  popd >/dev/null

  [[ -f "$project_dir/scripts/check.ps1" ]] || {
    printf 'Expected PowerShell check script.\n' >&2
    exit 1
  }
  [[ -f "$project_dir/scripts/fix.ps1" ]] || {
    printf 'Expected PowerShell fix script.\n' >&2
    exit 1
  }
  assert_file_contains "$project_dir/.pre-commit-config.yaml" 'powershell -ExecutionPolicy Bypass -File scripts/check.ps1'
  assert_file_contains "$agents_path" 'This project was generated by `new-project.ps1`.'
  assert_file_contains "$agents_path" 'Primary shell: PowerShell'
  assert_file_contains "$agents_path" '.\scripts\check.ps1'
  assert_file_contains "$agents_path" '.\scripts\fix.ps1'
}

run_bash_install_contract
run_windows_installer_static_contract
run_agents_contract
run_powershell_contract_if_available

printf 'cross-platform contract tests passed\n'
